### ISSUE TITLE
18 Places to Find Free Data Sets for Data Science Projects

### ISSUE THREAD

**Issue by rufuspollock** [datasets/awesome-data#265]
Another example of a meta-collection. Some of the items might be useful to add some collections pages or as their own page

https://www.dataquest.io/blog/free-datasets-for-projects/

## Tasks

* [ ] Extract list (or key items) of datasets to list here
* [ ] Analyse which could go to which existing collections plus if we need new collections
* [ ] Create a blog post
