### ISSUE TITLE
Bibliographic data

### ISSUE THREAD

**Issue by rufuspollock** [datasets/awesome-data#284]
**Awesome page in progress at: https://datahub.io/collections/bibliographic-data**

# What we Cover

Datasets we want to cover:

* Author metadata
* Article metadata
* Book metadata (bonus points if FRBR-like)

## Tasks

* [x] Stub page
* [ ] Embed the google docs spreadsheet overview - https://docs.google.com/spreadsheets/d/1Sx-MKTkAhpaB3VHiouYDgMQcH81mKwQtaK2-BXYbKkE/edit#gid=0
  * [ ] (Future) turn this into a CSV and show on page (?) then embed this as a mini data package
* [ ] Start adding sections for specific items with full description e.g. viaf, crossref (at some point these could move to datasets on datahub)

# State of play

I compiled a detailed spreadsheet (as of 2016) of the state of play here:

https://docs.google.com/spreadsheets/d/1Sx-MKTkAhpaB3VHiouYDgMQcH81mKwQtaK2-BXYbKkE/edit#gid=0

* CrossRef - has API but no official regular bulk dump - see https://github.com/CrossRef/rest-api-doc/issues/271
* OCLC: ???
* Book data: ...?

# Context

*These are the kind of questions / user stories I had*

* Could one build an "open" Google Scholar or an open "OCLC"
* If i wanted to build a "lookup" service for my reference manager what API could I use and what is the license on the data?
* Where can I find open (or just free) bibliography data
* Where can I find open (or just free) bibliography online services or APIs

User stories:

* I come across a book or article and i want to quickly get full biblio info for storing in a blog post or an article i am writing
* I come across a book or article title and want to look it up
* Ditto and i want to auto-save into my local bibliography

## Aim of research

- Identify existing databases or services providing substantial bibliographic data
- Can partition between books and papers as they are different
- Classify in key ways e.g. open or not etc

**Comment by miku** [comment]
In addition to sources already listed in the [spreadsheet](https://docs.google.com/spreadsheets/d/1Sx-MKTkAhpaB3VHiouYDgMQcH81mKwQtaK2-BXYbKkE/edit#gid=0), at the [Archive](https://archive.org/) we have a couple of items related to bibliographic metadata, especially this one:

* https://archive.org/details/ia_biblio_metadata

> This collection contains both external ("upstream") metadata dumps and Internet Archive generated databases and reports on our holdings of papers, books, and other documents.

**Comment by rufuspollock** [comment]
@miku very useful - thank-you!

**Comment by miku** [comment]
There's an upload of this dataset at: https://archive.org/details/crossref-2022-11-02 (139M docs).
