### ISSUE TITLE
What is the simplest way we could maintain github.com/datasets?

### ISSUE THREAD

**Issue by rufuspollock** [datasets/awesome-data#375]
Quite a few of the core datasets are not getting updated.

## Tasks

- [ ] Which datasets are "core" **✅2023-03-13 https://github.com/datasets/core-datasets**
- [ ] What non-core datasets are there?
- [ ] Which of these are up to date / out of date?
- [ ] Which github actions are failing
- [ ] How do we show a datasets is not up to date
  - [ ] Perhaps a GH badge?

**Comment by sabas** [comment]
I try to maintain my main dataset (UN/LOCODE) when I remember, perhaps it could be useful to have a way of monitoring when a new release is needed by scraping the page from which we grab the dataset?
